#!/bin/bash
# Builder modified: Mon July 06, 2020 @ 04:08:14 EDT

if [[ $UID != 0 ]]; then
    echo "Please run this script using sudo: "
    echo "sudo $0 $1"
    exit 1
fi

confirm="no"
until [ "$confirm" = "yes" ]; do
    confirm="no";
    echo ""
    read -p 'Specify SiteName (eg. "Google"): ' bld_sitename;
    read -p -N3 'Specify Three-Letter Abbreviation (eg. "goo"): ' bld_abbrev;
    echo "Just to confirm, you specified: ";
    echo "      sitename: $bld_sitename ";
    echo "      abbreviation: $bld_abbrev ";
    read "Is this correct? [Y/n] " response;
    response=${response,,};    # tolower
    if [[ "$response" =~ ^(yes|y)$ ]]; then
        confirm="yes";
    fi
done;
echo "";
echo "Creating Directories. Hold on to your seat!";
echo "[COMMAND] sudo mkdir -p /var/www/$bld_abbrev/html";
echo "[COMMAND] sudo mkdir -p /var/www/$bld_abbrev/logs";
echo "[COMMAND] sudo mkdir -p /etc/httpd/sites-available";
echo "[COMMAND] sudo mkdir -p /etc/httpd/sites-enabled";
echo "";
echo "Setting up permissions so SELinux doesn't throw a fit...";
echo " ~~~ What are you going to do SELinux? Cry? Piss your pants? Maybe shit and cum? ~~~ ";
echo "[COMMAND] sudo chown -R $USER:$USER /var/www/$bld_abbrev/html";
echo "[COMMAND] sudo chmod -R 755 /var/www";
echo '[COMMAND] sudo "emanage fcontext -a -t httpd_log_t "/var/www/$bld_abbrev/logs(/.*)?"';
echo "[COMMAND] sudo restorecon -R -v /var/www/$bld_abbrev/logs";
echo "";
echo "Reconfiguring Git environment.";
bld_self=$(git rev-parse --show-toplevel);
echo "[COMMAND] cd $bld_self/..";
echo "[COMMAND] sudo mkdir -p $bld_sitename";
echo "[COMMAND] sudo chown $USER:$USER $bld_sitename";
echo "[COMMAND] sudo mv $bld_self/* $bld_sitename";
echo "[COMMAND] cd $bld_sitename";
echo "[COMMAND] git init";
echo "";
echo "Generating default site.";
echo "[COMMAND] sudo mkdir -p pagesource/css";
echo "[COMMAND] wget some main.css";
echo "[COMMAND] wget Some index.html";
echo "[COMMAND] cd pagesource/css";
echo '''[COMMAND] (echo "\* AUTOGENERATED: $(date +'%c %Z') */" && cat main.css) > main1.css && mv main1.css main.css''';
echo "[COMMAND] cd ..";
echo '''[COMMAND] (echo "<!-- AUTOGENERATED: $(date +'%c %Z') -->" && cat index.html) > index1.html && mv index1.html index.html''';
echo "[COMMAND] cd ..";
bld_self=$(git rev-parse --show-toplevel 2>&1);
echo "New root set at $bld_self";
echo "[COMMAND] cd $bld_self";
echo "";
echo "Building some luxuries.";
echo "[COMMAND] mkdir .sh";
echo "[COMMAND] touch";
exit 0;
